on:
  schedule:
    # run every day at 11 PM
    - cron: '0 23 * * *'

jobs:
  build:
    env:
      CRAN: 'https://demo.rstudiopm.com/all/__linux__/xenial/latest'
    runs-on: ubuntu-latest
    container: rstudio/r-base:3.6-xenial
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Setup R
        uses: jimhester/setup-r@master
      - run: |
          R -e 'install.packages(c("BiocManager", "remotes"))'
          R -e 'remotes::install_deps()'
      - name: Install pandoc
        env:
          PANDOC_VERSION: 2.7.3
        run: |
           curl -fLo /tmp/pandoc.pkg "https://github.com/jgm/pandoc/releases/download/${PANDOC_VERSION}/pandoc-${PANDOC_VERSION}-macOS.pkg"
           sudo installer -pkg "/tmp/pandoc.pkg" -target /
           rm /tmp/pandoc.pkg
      - name: Install XQuartz
        env:
          XQUARTZ_VERSION: 2.7.11
        run: |
           curl -fLo /tmp/XQuartz.dmg "https://dl.bintray.com/xquartz/downloads/XQuartz-${XQUARTZ_VERSION}.dmg"
           sudo hdiutil attach -noverify /tmp/XQuartz.dmg
           sudo installer -pkg "/Volumes/XQuartz-${XQUARTZ_VERSION}/XQuartz.pkg" -target /
           sudo hdiutil detach /Volumes/XQuartz-${XQUARTZ_VERSION}
           rm /tmp/XQuartz.dmg
      - name: Install hugo
        run: |
          R -e 'blogdown::install_hugo()'
      - name: Build site
        run: |
          # We need to update the timestamps so this is re-built
          touch content/home/demo.Rmd
          R -e 'blogdown::build_site(TRUE)'
      - name: Install npm
        uses: actions/setup-node@v1
      - name: Deploy to Netlify
        # NETLIFY_AUTH_TOKEN added in the repo's secrets
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          npm install netlify-cli -g
          netlify deploy --prod
